movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.main, name='main'),
    path('index/', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/update/ ', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

pjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('reviews/', include('movies.urls')),
]

movies/models.py
from email.policy import default
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator


# Create your models here.
class Movie(models.Model):
  title = models.CharField(max_length=20)
  content = models.TextField()
  movie_name = models.CharField(max_length=20)
  grade = models.IntegerField(default=10,validators=[MinValueValidator(0),MaxValueValidator(10)])
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)
  view_count = models.IntegerField(default=0)

movies/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = '__all__'
        exclude = ['created_at', 'updated_at', 'view_count']
        labels = {
        'title' : '리뷰 제목',
        'content' : '리뷰 내용',
        'movie_name' : '영화 제목',
        'grade' : '평점(0~10)',
        }

movies/views.py
from django.shortcuts import render, redirect
from movies.forms import MovieForm
from .models import Movie

# Create your views here.
def main(request):

  return render(request, 'movies/main.html')

def index(request):
  movie = Movie.objects.order_by('-created_at')
  context = {
    'movies':movie,
  }

  return render(request, 'movies/index.html', context)

def detail(request, pk):
  movie = Movie.objects.get(pk=pk)
  cnt = movie.view_count
  cnt += 1
  movie.view_count = cnt
  movie.save()
  context={
    'movie':movie,
  }
  return render(request, 'movies/detail.html', context)

def create(request):
  if request.method == 'POST':
    movies = MovieForm(request.POST)
    if movies.is_valid():
      movie_detail = movies.save()
      return redirect('movies:detail', movie_detail.pk)
  else:
    movies = MovieForm()
  context = {
    'movies': movies,
  }
  return render(request, 'movies/form.html', context)

def update(request, pk):
  movie = Movie.objects.get(pk=pk)
  if request.method == 'POST':
    movies = MovieForm(request.POST, instance=movie)
    if movies.is_valid():
      movie_detail = movies.save()
      return redirect('movies:detail', movie_detail.pk)
  else:
    movies = MovieForm(instance=movie)
  context = {
    'movie': movie,
    'movies': movies,
  }
  return render(request, 'movies/form.html', context)

def delete(request, pk):
  movie = Movie.objects.get(pk=pk)
  if request.method == 'POST':
    movie.delete()
    return redirect('movies:index')
  else:
    return redirect('movies:detail', movie.pk)

movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block body %}
  <h1 class="text-center">{{ movie.title }}</h1>
  <hr>
  <h3>{{ movie.movie_name }}</h3>
  <hr>
  <p>{{ movie.content }}</p>
  <div class="float-end">
    <div class="d-flex align-items-end">
      <form action="{% url 'movies:update' movie.pk %}">
        <button type="submit" class="btn btn-outline-dark mx-2 fw-bold">수정</button>
      </form>
      <button type="button" class="btn btn-outline-dark mx-2 fw-bold" data-bs-toggle="modal" data-bs-target="#exampleModal">
        삭제
      </button>
      <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-body">
              <h4>정말 삭제하시겠습니까?</h4>
              <div class='float-end'>
                <div class='d-flex'>
                  <form action="{% url 'movies:delete' movie.pk %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-outline-danger mx-2 fw-bold">삭제</button>
                  </form>
                  <button type="button" class="btn btn-outline-dark" data-bs-dismiss="modal">닫기</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock body %}

movies/templates/movies/form.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block body %}
  {% if request.resolver_match.url_name == 'create' %}
    <h1 class="text-center fw-bold">리뷰 작성</h1>
  {% else %}
    <h1 class="text-center fw-bold">리뷰 수정</h1>
  {% endif %}
  <form action="" method='POST'>
    {% csrf_token %}
    {% bootstrap_form movies %}
    <input class="btn btn-outline-dark w-100" type="submit">
  </form>
{% endblock body %}

movies/templates/movies/index.html
{% extends 'base.html' %}

{% block body %}
  <h1 class="text-center mb-5 fw-bold">Movie Reviews</h1>

  <ol class="list-group list-group-numbered">
    {% for movie in movies %}
      <li class="list-group-item d-flex justify-content-between align-items-start">
        <div class="ms-2 me-auto">
          <div class="fw-bold">{{ movie.movie_name }}</div>
          <a style="font-size:30px; color:black; text-decoration: none;" href="{% url 'movies:detail' movie.pk %}">{{ movie.title }}</a>
          <p class="mt-2 mb-1">{{ movie.created_at }}
            |
            {{ movie.updated_at }}</p>
        </div>
        <span class="badge bg-primary rounded-pill mx-1">조회수
          {{ movie.view_count }}
        </span>
        <span class="badge bg-danger rounded-pill mx-1">평점
          {{ movie.grade }}
        </span>
      </li>
    {% endfor %}
  </ol>
  <!-- {% for movie in movies %} <p> <a href="{% url 'movies:detail' movie.pk %}">{{ movie.title }}</a> {{ movie.movie_name }} </p> {% endfor %} -->
{% endblock body %}

movies/templates/movies/main.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static 'imgs/001.jpg' %}" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item active">
        <img src="{% static 'imgs/002.jpg' %}" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item active">
        <img src="{% static 'imgs/003.jpg' %}" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item active">
        <img src="{% static 'imgs/004.jpg' %}" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item active">
        <img src="{% static 'imgs/005.jpg' %}" class="d-block w-100" alt="...">
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
  <h1 class="text-center my-5 fw-bold">영화 순위</h1>
  <section class="container my-3">
    <div class="row g-3">
      <div class="col-12 col-sm-12 col-md-6 col-lg-4">
        <div class="card text_photo">
          <a class="card-url" href="">
            <img src="{% static 'imgs/movie1.jpg' %}" class="card-img-top" id="hvr-img" alt="..."/>
          </a>
          <div class="card-body movie_card">
            <h5 class="card-title fw-bold">1. 쇼생크 탈출</h5>
            <a href="#" class="btn btn-outline-dark">예매하기</a>
          </div>
        </div>
      </div>
      <div class="col-12 col-sm-12 col-md-6 col-lg-4">
        <div class="card text_photo">
          <a class="card-url" href="">
            <img src="{% static 'imgs/movie2.jpg' %}" class="card-img-top" id="hvr-img" alt="..."/>
          </a>
          <div class="card-body movie_card">
            <h5 class="card-title fw-bold">2. 죽은 시인의 사회</h5>
            <a href="#" class="btn btn-outline-dark">예매하기</a>
          </div>
        </div>
      </div>
      <div class="col-12 col-sm-12 col-md-6 col-lg-4">
        <div class="card text_photo">
          <a class="card-url" href="">
            <img src="{% static 'imgs/movie3.jpg' %}" class="card-img-top" id="hvr-img" alt="..."/>
          </a>
          <div class="card-body movie_card">
            <h5 class="card-title fw-bold">3. 다크 나이트 라이즈</h5>
            <a href="#" class="btn btn-outline-dark">예매하기</a>
          </div>
        </div>
      </div>
      <div class="col-12 col-sm-12 col-md-6 col-lg-4">
        <div class="card text_photo">
          <a class="card-url" href="">
            <img src="{% static 'imgs/movie4.jpg' %}" class="card-img-top" id="hvr-img" alt="..."/>
          </a>
          <div class="card-body movie_card">
            <h5 class="card-title fw-bold">4. 그랜드 부다페스트 호텔</h5>
            <a href="#" class="btn btn-outline-dark">예매하기</a>
          </div>
        </div>
      </div>
      <div class="col-12 col-sm-12 col-md-6 col-lg-4">
        <div class="card text_photo">
          <a class="card-url" href="">
            <img src="{% static 'imgs/movie5.jpg' %}" class="card-img-top" id="hvr-img" alt="..."/>
          </a>
          <div class="card-body movie_card">
            <h5 class="card-title fw-bold">5. 그녀</h5>
            <a href="#" class="btn btn-outline-dark">예매하기</a>
          </div>
        </div>
      </div>
      <div class="col-12 col-sm-12 col-md-6 col-lg-4">
        <div class="card text_photo">
          <a class="card-url" href="">
            <img src="{% static 'imgs/movie6.jpg' %}" class="card-img-top" id="hvr-img" alt="..."/>
          </a>
          <div class="card-body movie_card">
            <h5 class="card-title fw-bold">6. 위대한 쇼맨</h5>
            <a href="#" class="btn btn-outline-dark">예매하기</a>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

templates/base.html
{% load django_bootstrap5 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@500&display=swap" rel="stylesheet">
    <style>
      body {
        font-family: 'Noto Sans KR', sans-serif;
      }
    </style>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'movies:main' %}"><img src="{% static 'imgs/logo.jpg'%}" alt="로고이미지" style="width: 7rem;"></a>
        <div class="collapse navbar-collapse" id="navbarNav"></div>
      </div>
    </nav>
    <div class="d-flex h-100">
      <aside class="position-sticky top-0 pt-3 bg-dark" style="min-width:10rem; width:10rem; height:100vh;">
        <nav class="nav flex-column text-center">
          <a class="nav-link text-light" href="{% url 'movies:index' %}">영화 목록</a>
          <a class="nav-link text-light" href="{% url 'movies:create' %}">영화 작성</a>
        </nav>
      </aside>
      {% if request.resolver_match.url_name == 'main' %}
        <content>
          {% block content %}{% endblock content %}
        </content>
      {% else %}
        <content class="container mt-4">
          {% block body %}{% endblock body%}
        </content>
      {% endif %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>

</html>